version: "3.9"
services:
  nginx:
    image: luckwheat.com/notes-nginx:0.1
    ports:
      - "80:80"
    environment:
      CLIENT_APP_URL: front-app:3000
      API_SERVER_URL: api-server:8080
    depends_on:
      - api-server
      - front-app
  api-server:
    image: luckwheat.com/notes-storage-service:0.1-SNAPSHOT
    depends_on:
      - db
      - elasticsearch
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      DB_URL: jdbc:postgresql://db:5432/${DB_NAME}
      DB_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      DB_USERNAME: ${DB_USER}
      DB_PASSWORD: ${DB_PWD}
      DB_DRIVER: org.postgresql.Driver
      ELASTICSEARCH_URL: http://elasticsearch:9200
      OAUTH_JWKS_URI: ${OAUTH_JWKS_URI}
      OAUTH_ISSUER_URL: ${OAUTH_ISSUER_URL}
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
  front-app:
    image: luckwheat.com/notes-app:0.1
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://nginx
      REACT_APP_AUTH0_CLIENT_ID: ${REACT_APP_AUTH0_CLIENT_ID}
      REACT_APP_AUTH0_DOMAIN: ${REACT_APP_AUTH0_DOMAIN}
      REACT_APP_AUTH0_CALLBACK_URL: ${REACT_APP_AUTH0_CALLBACK_URL}
      REACT_APP_AUTH0_AUDIENCE: ${REACT_APP_AUTH0_AUDIENCE}
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PWD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata-notes-storage:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  elasticsearch:
    image: elasticsearch:5.6
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx1g
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
volumes:
  pgdata-notes-storage:
    external: true