version: "3.9"
services:
  notes-storage:
    depends_on:
      - db
    image: luckwheat.com/notes-storage-service:0.1-SNAPSHOT
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://db:5432/${DB_NAME}
      DB_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      DB_USERNAME: ${DB_USER}
      DB_PASSWORD: ${DB_PWD}
      DB_DRIVER: org.postgresql.Driver
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PWD}
      POSTGRES_DB: ${DB_NAME}
