micronaut:
  application:
    name: notesStorageService
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
datasources:
  default:
    url: ${DB_URL}
    driverClassName: ${DB_DRIVER}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    schema-generate: CREATE
    dialect: ${DB_DIALECT}
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: none
          show_sql: true
jpa.default.entity-scan.pakage: com.luckwheat.notes.entity
liquibase:
  enabled: true
  datasources:
    default:
      enabled: true
      change-log: 'classpath:db/liquibase-changelog.xml'
netty:
  default:
    allocator:
      max-order: 3
