micronaut:
  application:
    name: notesStorageService
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  security:
    authentication: bearer
    enabled: true
    token:
      jwt:
        enabled: true
        claims-validators:
          issuer: ${OAUTH_ISSUER_URL}
        signatures:
          jwks:
            auth0:
              url: ${OAUTH_JWKS_URI}
    endpoints:
      logout:
        get-allowed: true
datasources:
  default:
    url: ${DB_URL}
    driverClassName: ${DB_DRIVER}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    schema-generate: CREATE
    dialect: ${DB_DIALECT}
jpa:
  default:
    properties:
        hbm2ddl:
          auto: none
          show_sql: true
jpa.default.entity-scan.pakage: com.luckwheat.notes.entity
hibernate:
  search:
    default:
      indexmanager: elasticsearch
      elasticsearch:
        host: ${ELASTICSEARCH_URL}
        required_index_status: yellow
liquibase:
  enabled: true
  datasources:
    default:
      enabled: true
      change-log: 'classpath:db/liquibase-changelog.xml'
netty:
  default:
    allocator:
      max-order: 3
