on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1                  
  
  ECS_CLUSTER: notes-ec2                 
  
  NOTES_SERVICE_ECR_REPOSITORY: notes-service     
  NOTES_SERVICE_ECS_SERVICE: notes-service-ec2
  NOTES_SERVICE_ECS_TASK_DEFINITION: .github/aws/notes-service-taskdef.json 
  NOTES_SERVICE_CONTAINER_NAME: notes-service
  
  NOTES_APP_ECR_REPOSITORY: notes-app
  NOTES_APP_ECS_SERVICE: notes-app-ec2
  NOTES_APP_ECS_TASK_DEFINITION: .github/aws/notes-app-taskdef.json
  NOTES_APP_CONTAINER_NAME: notes-app-ec2
  
jobs:
  build-notes-service:
    runs-on: ubuntu-latest
    name: Build and Deploy Notes Backend Service
    steps:
      - name: Checkout
        uses: actions/checkout@v2.6.0
      - name: Setup Java JDK
        uses: actions/setup-java@v3.9.0
        with:
          java-version: 18
          distribution: adopt
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@13d241b293754004c80624b5567555c4a39ffbe3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@aaf69d68aa3fb14c1d5a6be9ac61fe15b48453a2
      - name: Clean and prepare
        run: mvn clean mn:dockerfile -Dpackaging=docker
      - name: Maven install (with docker image build)
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: | 
          mvn install -Dpackaging=jar -Ddocker.repository=$ECR_REGISTRY/$NOTES_SERVICE_ECR_REPOSITORY -Ddocker.tag=$IMAGE_TAG
          docker push $ECR_REGISTRY/$NOTES_SERVICE_ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$NOTES_SERVICE_ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@97587c9d45a4930bf0e3da8dd2feb2a463cf4a3a
        with:
          task-definition: ${{ env.NOTES_SERVICE_ECS_TASK_DEFINITION }}
          container-name: ${{ env.NOTES_SERVICE_CONTAINER_NAME }}
          image: ${{ steps.build-image.outputs.image }}
      - name: Deploy to AWS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ env.NOTES_SERVICE_ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true     
  build-notes-app:
    runs-on: ubuntu-latest
    name: Build and Deploy Notes App 
    steps:
      - name: Checkout
        uses: actions/checkout@v2.6.0
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@13d241b293754004c80624b5567555c4a39ffbe3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}   
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@aaf69d68aa3fb14c1d5a6be9ac61fe15b48453a2
      - name: Create Env
        run: echo -e "REACT_APP_API_URL=$REACT_APP_API_URL
          \nREACT_APP_AUTH0_AUDIENCE=$REACT_APP_AUTH0_AUDIENCE
          \nREACT_APP_AUTH0_CALLBACK_URL=$REACT_APP_AUTH0_CALLBACK_URL
          \nREACT_APP_AUTH0_CLIENT_ID=$REACT_APP_AUTH0_CLIENT_ID
          \nREACT_APP_AUTH0_DOMAIN=$REACT_APP_AUTH0_DOMAIN" >> ./webclient/notes-storage-app/.env
        env: 
          REACT_APP_API_URL: ${{ secrets.APP_API_URL }}
          REACT_APP_AUTH0_AUDIENCE: ${{ secrets.AUTH0_AUDIENCE }}
          REACT_APP_AUTH0_CALLBACK_URL: ${{ secrets.AUTH0_CALLBACK_URL }}
          REACT_APP_AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
          REACT_APP_AUTH0_DOMAIN:  ${{ secrets.AUTH0_DOMAIN }}    
      - name: Build Image
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$NOTES_APP_ECR_REPOSITORY:$IMAGE_TAG ./webclient/notes-storage-app
          docker push $ECR_REGISTRY/$NOTES_APP_ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$NOTES_APP_ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@97587c9d45a4930bf0e3da8dd2feb2a463cf4a3a
        with:
          task-definition: ${{ env.NOTES_APP_ECS_TASK_DEFINITION }}
          container-name: ${{ env.NOTES_APP_CONTAINER_NAME }}
          image: ${{ steps.build-image.outputs.image }}
      - name: Deploy to AWS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ env.NOTES_APP_ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true 
