on: [push, pull_request]

jobs:
  build-backend:
    runs-on: ubuntu-latest
    name: Build backend
    steps:
      - name: Checkout
        uses: actions/checkout@v2.6.0
      - name: Setup Java JDK
        uses: actions/setup-java@v3.9.0
        with:
          java-version: 18
          distribution: adopt
      - name: Clean and prepare
        run: mvn clean mn:dockerfile -Dpackaging=docker
      - name: Maven install 
        run: mvn install -Dpackaging=jar
  build-nginx:
    runs-on: ubuntu-lates
    name: build NGiNX
    steps:
      - name: Checkout
        uses: actions/checkout@v2.6.0
      - name: Build Docker Image
        run: docker build -t artyompanfutov/notes-nginx:0.1 ./nginx
      
